import type { CategoryId } from '../categories';

// Hand-curated question bank shipped with the app. Used as the fallback when
// AI providers are unavailable or disabled. Each category has 30-40 prompts
// to keep variety high across many recordings.

const banks: Record<CategoryId, string[]> = {
  pre_game: [
    'How are you feeling about this game?',
    'What position are you playing today?',
    'What is one thing you want to work on out there?',
    'Who are you most excited to play with today?',
    'What would a great game look like for you?',
    'How do you calm down when you feel nervous?',
    'What did Coach say in practice this week that stuck with you?',
    'What is your warm-up routine?',
    'If today goes really well, what does that look like?',
    'What part of your game do you feel best about right now?',
    'What part of the other team are you watching out for?',
    'What is one small thing you want to remember when you step on the field?',
    'What did you eat or drink to get ready?',
    'What song are you hyping yourself up with?',
    'What is your secret weapon today?',
    'Who is going to be watching, and how does that feel?',
    'If someone gave you one piece of advice right before the game, what would help most?',
    'What is the goal of the team today?',
    'What is your personal goal today?',
    'What is one thing you do not want to do today?',
    'What is the weather doing — is it in your favor?',
    'How is your body feeling — anything tight or sore?',
    'What is the toughest matchup you might face?',
    'Tell me about one teammate you are counting on.',
    'What is your pre-game ritual?',
    'What is something Coach has been drilling you on lately?',
    'What is one fear you want to leave in the parking lot?',
    'What is one strength you want to bring out today?',
    'How long have you been waiting for this game?',
    'What does a win feel like in your body before it happens?',
    'What is the dumbest superstition you secretly believe?',
    'If this game had a soundtrack, what is the first song?',
    'What is one thing you want me to notice about you today?',
    'What is one mistake you are okay with making today?',
    'Who taught you the move you are going to use first?',
    'How are your nerves on a scale of one to ten?',
  ],
  post_game: [
    'What was your favorite moment from today?',
    'Tell me about a play you want to remember.',
    'What is one thing you did out there that you are proud of?',
    'What was the hardest part of today?',
    'If you could replay one moment, which would it be and why?',
    'What is one thing you learned about yourself today?',
    'How did the team feel out there together?',
    'Did anything surprise you about how the game went?',
    'What did Coach say to you after the game?',
    'How do your legs and arms feel right now?',
    'What do you want to work on before the next game?',
    'Was there a teammate who did something that stood out to you?',
    'What is something you tried today that you have never tried before?',
    'What was the funniest thing that happened out there?',
    'If today were a movie scene, what would the title be?',
    'What was going through your head during the biggest moment?',
    'Was there a moment you almost gave up — and what kept you going?',
    'What is one thing the other team did that you respect?',
    'What did the bench feel like today?',
    'How would you grade your own effort today?',
    'How would you grade your own focus today?',
    'What was the weirdest moment of the game?',
    'Was there a play that did not work out the way you hoped?',
    'What is the one thing you want to remember from this game in ten years?',
    'Who would you give the game ball to, and why?',
    'What did you eat or drink during the game that helped or hurt?',
    'Was there a moment when the crowd really got into it?',
    'What is something you noticed today that nobody else might have seen?',
    'How did Coach\'s words land with you today?',
    'What is one thing the team did differently from last time?',
    'If you could thank one person for today, who and why?',
    'What is your number-one lesson from today?',
    'What was the loudest moment of the game for you?',
    'What was the quietest moment?',
    'What was the most fun moment?',
    'What is one thing you are taking into the next practice?',
  ],
  moment: [
    'What was going through your head right then?',
    'What did that feel like?',
    'Did you see it coming, or did it surprise you?',
    'What were you trying to do on that play?',
    'What did you tell yourself in that moment?',
    'Walk me through what you saw out there.',
    'What happens the next time you get that same play?',
    'What did your teammates do right after?',
    'What do you want to remember about that moment?',
    'If that play could go a little differently, what would you change?',
    'What was the hardest part of that play?',
    'How are your hands feeling right now?',
    'How is your heart feeling right now?',
    'What is the first thought that hit you when it happened?',
    'Did anyone say something to you right after?',
    'What did you almost do instead?',
    'What were you most proud of in that moment?',
    'What scared you most in that moment?',
    'How did Coach react?',
    'What did the other team do?',
    'What did the crowd do?',
    'How would you describe that moment to someone who was not there?',
    'If you could freeze that moment and study it, what would you notice?',
    'What was the muscle memory that kicked in?',
    'What did you hear right before it happened?',
    'How did time feel — fast or slow?',
    'What do you want to do right now to reset?',
    'What does this moment teach you?',
    'Who had your back right after?',
    'How will you tell this story to a friend tonight?',
  ],
  season: [
    'What is your favorite memory from this season so far?',
    'Who on the team makes you laugh the most?',
    'What is something you can do now that you could not do at the start of the season?',
    'What is the biggest thing you have learned this season?',
    'Who on this team has helped you the most, and how?',
    'What is a goal you have for the rest of the season?',
    'If you could pick any game from this year to play again, which one and why?',
    'What has been the hardest part of the season for you?',
    'What do you love most about playing this sport?',
    'Where do you want to be by the end of the season?',
    'What is the funniest thing that has happened all year?',
    'What does this team feel like compared to teams you played on before?',
    'Who has been the unexpected leader of the team?',
    'What is one thing you wish you could change about how things have gone?',
    'What is the biggest moment of growth you have noticed in yourself?',
    'What is the biggest moment of growth you have noticed in a teammate?',
    'How has Coach changed how you see the game?',
    'What is a tradition or inside joke from this season you want to remember?',
    'When did this group really start to feel like a team?',
    'What is one thing you want to do differently next season?',
    'What do you want next year\'s version of this team to know?',
    'Who has surprised you this season?',
    'What is one thing you are tired of?',
    'What is one thing you are not ready to let go of yet?',
    'How would you describe this season in three words?',
    'What is the hardest game you played, and why?',
    'What is the best feeling you have had on the field this year?',
    'What part of the game makes the most sense to you now compared to last year?',
    'What would you tell yourself at the start of the season if you could go back?',
    'Who have you become tighter with this year?',
    'What do you love about your jersey number?',
    'What do you love about being this age and playing this sport?',
  ],
  before_school: [
    'What is one thing you are looking forward to today?',
    'What is one thing you are dreading?',
    'Who do you most want to see at school today?',
    'Is there a class today you are excited about?',
    'Is there a class today you wish you could skip?',
    'What is in your backpack besides books today?',
    'How is your brain feeling — sleepy, sharp, fuzzy?',
    'What did you dream about last night, if you remember?',
    'What is something you want to try saying or doing today?',
    'Is there a friend you want to make plans with after school?',
    'What is something you are nervous about?',
    'What is something you are confident about?',
    'Did you finish all your homework, or is something hanging over you?',
    'Is there a test, presentation, or project today?',
    'What outfit are you wearing — and why?',
    'What is for lunch, and how do you feel about it?',
    'What is a question you might ask a teacher today?',
    'Is there a teacher you want to thank or compliment?',
    'Is there a teacher you are bracing yourself for?',
    'What song would help you start the day?',
    'What is one promise you want to make to yourself for today?',
    'Is there a worry you want to leave at the door?',
    'What is something kind you could do for a classmate today?',
    'How are your nerves about being seen today?',
    'What is one thing you are NOT going to do today?',
    'How does your stomach feel right now?',
    'What is the first thing you want to do when you get there?',
    'Is there a hallway or classroom that feels like yours?',
    'What is a small win that would make today feel good?',
    'What is one thing you want to remember to tell me when I see you later?',
    'What is the weather, and how does it match your mood?',
    'If today went perfectly, what would happen?',
    'What is a tiny thing you are excited about that nobody else would notice?',
  ],
  after_school: [
    'What is one thing that happened today that surprised you?',
    'Who did you spend time with at lunch?',
    'Was there a moment today when you laughed out loud?',
    'What did you learn that you want to remember?',
    'Was there anything that was harder than you expected?',
    'Who was kind to you today, and how?',
    'Were you kind to anyone today?',
    'What was the most boring part of the day?',
    'What was the most interesting thing a teacher said?',
    'Did anything happen today that you want to talk about later?',
    'What is one thing you want to try tomorrow?',
    'How are you feeling about school right now?',
    'What was the best part of your day?',
    'Did you raise your hand for anything today?',
    'Did anything embarrassing happen that you can laugh about now?',
    'Who made you feel seen today?',
    'Was there a class that flew by, and one that dragged?',
    'What did you doodle or scribble during class?',
    'What is the funniest thing a friend said to you today?',
    'What is a question you wished you had asked in class?',
    'Did you eat anything weird at lunch?',
    'What was the rumor or news of the day?',
    'How is that one project / paper / test going?',
    'Was there anyone you wanted to talk to but did not?',
    'What was the song stuck in your head?',
    'What is something you saw on the way home?',
    'How did the bus / drop-off / pickup go?',
    'Who did you sit next to in class?',
    'What did you read or hear today that made you think?',
    'Is there something a teacher noticed about you?',
    'What is one thing you want to tell a friend tomorrow?',
    'Was there a moment when you felt totally yourself today?',
    'Was there a moment when you felt out of place?',
    'How does your backpack feel — heavy or light?',
    'What is one thing that went better than yesterday?',
  ],
  end_of_day: [
    'What was the best part of your day?',
    'Was there a hard part of the day you want to talk about?',
    'What is something you noticed today that other people might not have?',
    'What is something you are grateful for tonight?',
    'What is something you are looking forward to tomorrow?',
    'Is there anything you wish had gone differently today?',
    'Who do you want to thank for something today?',
    'What was the funniest thing you heard or saw today?',
    'How is your body feeling right now?',
    'What is one thing you are proud of from today?',
    'What is one thing you forgave yourself for today?',
    'What was the most beautiful thing you saw?',
    'What are you bringing into tomorrow?',
    'What are you leaving behind today?',
    'Did you cry today, even a little?',
    'Did you laugh hard today?',
    'What did you learn about yourself today?',
    'What did you learn about someone else today?',
    'Is there a worry you want to set down before you sleep?',
    'Is there something you want to tell me before bed?',
    'What was the kindest thing you did?',
    'What was the kindest thing someone did for you?',
    'How would you rate today on a scale of one to ten — and why?',
    'What is the one thing you want to remember from today?',
    'Was there a moment today that felt like it might be a memory someday?',
    'What did your favorite person do today?',
    'What is the smell or sound from today that stays with you?',
    'Was there a moment when you felt brave?',
    'Was there a moment when you felt loved?',
    'What is your wish for tomorrow?',
    'What story do you want me to tell you tonight?',
    'What is the last good thing that happened today?',
  ],
  big_feeling: [
    'Can you describe the feeling — what does it feel like in your body?',
    'When did you first start feeling this way?',
    'What do you think made the feeling start?',
    'Has this feeling ever shown up before? What did it look like then?',
    'If the feeling could talk, what would it say?',
    'What helps when you feel this way?',
    'Who do you most want with you when you feel like this?',
    'What is one tiny thing that might help right now?',
    'Is there something you want me to know but it is hard to say out loud?',
    'What do you want to do with this feeling next?',
    'If this feeling had a color, what color would it be?',
    'If this feeling had a weather, what would the sky look like?',
    'Where in your body do you feel it most?',
    'Is the feeling getting louder or quieter as we talk?',
    'What does this feeling want you to know?',
    'Is there a part of you that is okay even with this feeling here?',
    'What is something you do not want to hear right now?',
    'What is something you do want to hear right now?',
    'Has anyone you trust felt something like this?',
    'What is the smallest thing you could do for yourself right now?',
    'What were you doing right before the feeling showed up?',
    'Is there anyone you want to call or hug?',
    'Does the feeling have a name you would give it?',
    'What is the difference between this feeling and ones you have had before?',
    'How long do you think this feeling needs to be here?',
    'What is the worst part of this feeling?',
    'Is there any tiny part of it that is good?',
    'Would it help if we just sat together for a minute?',
    'What is one breath we can take together right now?',
    'If you closed your eyes, where would you go in your mind?',
    'What is the kindest thing you could say to yourself right now?',
    'What story would you tell a younger sibling who felt this way?',
  ],
  milestone: [
    'How does today feel different from any other day?',
    'What is something you want to remember from this exact moment?',
    'Who is someone you want to thank for helping you get here?',
    'What surprised you about getting to this point?',
    'What is something you can do now that you could not before?',
    'What advice would you give to a younger version of you?',
    'What is the next thing you want to work toward?',
    'How do you want to celebrate this?',
    'If you could send one message to your future self, what would it be?',
    'What do you hope is still true about you a year from now?',
    'How does your body feel today, knowing what today is?',
    'What is one tradition you want to start today?',
    'Who is someone you wish was here?',
    'What does growing up feel like right now?',
    'What is something you are leaving behind?',
    'What is something you are taking with you?',
    'What is the photo you want to remember today by?',
    'What word would you put on a banner over today?',
    'What is one thing that has been a long time coming?',
    'What do you want to be known for at this age?',
    'What is one promise you want to make to yourself?',
    'What is the smallest detail of today that you do not want to forget?',
    'What is the song you want to play loud today?',
    'What is a wish you want to set into the world today?',
    'What is something you used to be afraid of that you are not anymore?',
    'What is something that still scares you a little?',
    'How did you imagine this day when you were younger?',
    'How is the real version different from how you imagined it?',
    'What did the people who love you do to make this day special?',
    'What did YOU do to make this day special for someone else?',
    'What is the one moment from today that hit you in the chest?',
  ],
  trip: [
    'What was your favorite moment from the trip?',
    'What was something that surprised you?',
    'Was there a person you met or saw you want to remember?',
    'What did you eat that you want to have again?',
    'What was the funniest thing that happened?',
    'Was there a moment that was hard, and how did you get through it?',
    'What is something you want to bring home with you, even if it is just an idea?',
    'Where do you want to go next, and why?',
    'What did you learn about yourself on this trip?',
    'What did you learn about the people you traveled with?',
    'What was the best meal?',
    'What was the weirdest meal?',
    'What was your favorite smell from the trip?',
    'What was the most beautiful thing you saw?',
    'What was the longest you went without your phone, and how did that feel?',
    'What was the most photogenic moment?',
    'What was a moment you did NOT take a photo of, and why?',
    'Were there any languages or accents you noticed?',
    'What is a word you learned that you want to keep using?',
    'Who in the family handled the trip best?',
    'Who in the family struggled the most, and why?',
    'What was the longest car / train / plane ride like?',
    'What was the silliest souvenir you wanted?',
    'What was the silliest souvenir you actually got?',
    'Was there a moment you got homesick — what was it?',
    'Was there a moment you wished you could stay forever — what was it?',
    'Did anything go wrong that you can laugh about now?',
    'What is one thing you want to do differently next trip?',
    'What is one tradition you want to bring back home?',
    'What did the inside of your suitcase look like at the end of the trip?',
    'What is one thing you saw that made you say "I have never seen anything like this"?',
  ],
  open: [
    'What is something nobody knows about you yet?',
    'What is something you are wondering about lately?',
    'If you could have one superpower for a day, what would you do with it?',
    'Who is somebody you really admire, and why?',
    'What is something you want to be known for?',
    'What is the best thing about being your age right now?',
    'What is the hardest thing about being your age right now?',
    'What do you hope changes about the world by the time you grow up?',
    'What is a question you wish someone would ask you?',
    'What is something silly you do that makes you happy?',
    'What is your earliest memory?',
    'What is the best thing you have ever eaten?',
    'What is your favorite weather, and why?',
    'What is a song you can listen to a hundred times?',
    'What is the funniest joke you know?',
    'What is something you used to believe that you do not anymore?',
    'What is something you used to like that you do not anymore?',
    'What is something you used to NOT like that you love now?',
    'If you could live in any time period, when would it be?',
    'If you could be any age for a day, what would it be?',
    'What is your favorite room in our home, and why?',
    'What is a perfect Saturday for you?',
    'What is the best advice you have ever heard?',
    'What is the worst advice you have ever heard?',
    'What is something kids your age understand that grown-ups don\'t?',
    'What is something grown-ups understand that you wish they would explain better?',
    'Who in our family makes you feel safest?',
    'Who in our family makes you laugh the hardest?',
    'What is a dream you have had that stuck with you?',
    'What is something you want to do before you turn 18?',
    'What is one thing you have always wanted to ask me?',
    'What does love feel like to you?',
    'What does friendship feel like to you?',
    'What does home feel like to you?',
    'What is the bravest thing you have ever done?',
    'What is the kindest thing you have ever done?',
  ],
};

function shuffleAndTake<T>(arr: T[], n: number): T[] {
  const copy = arr.slice();
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(n, copy.length));
}

export function pickFallbackQuestions(
  category: CategoryId,
  count: number
): string[] {
  const bank = banks[category] ?? [];
  return shuffleAndTake(bank, count);
}

export function fallbackBankSize(category: CategoryId): number {
  return (banks[category] ?? []).length;
}
